name: Build and Deploy to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract tag parts
        id: extract_tag
        run: |
          TAG=${GITHUB_REF_NAME}
          MAJOR=$(echo $TAG | cut -d. -f1)
          MINOR=$(echo $TAG | cut -d. -f1-2)
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV
          echo "MINOR=${MINOR}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/go-page-process:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/go-page-process:${{ env.MAJOR }}
            ${{ secrets.DOCKER_USERNAME }}/go-page-process:${{ env.MINOR }}