name: Build multi-platform Docker image
 
on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-with-docker:
    name: Build multi-platform Docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set default docker tag label
        run: |
          echo "TAG1=latest" >> $GITHUB_ENV |
          echo "TAG2=" >> $GITHUB_ENV

      - name: Set docker tag label for git branches
        if: startsWith(github.ref, 'refs/heads/')
        run: echo "TAG1=${{ vars.DOCKER_USERNAME }}/go-page-process:$( echo $GITHUB_REF | cut -d / -f 3- )" >> $GITHUB_ENV

      - name: Set docker tag label for git tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "TAG1=${{ vars.DOCKER_USERNAME }}/go-page-process:$( echo $GITHUB_REF | cut -d / -f 3- )" >> $GITHUB_ENV |
          echo "TAG2=${{ vars.DOCKER_USERNAME }}/go-page-process:$( echo $GITHUB_REF | cut -d / -f 3- | cut -d . -f 1-2 )" >> $GITHUB_ENV

      - name: Set docker tag label for pull requests
        if: startsWith(github.ref, 'refs/pull/')
        run: echo "TAG1=p${{ vars.DOCKER_USERNAME }}/go-page-process:pr$( echo $GITHUB_REF | cut -d / -f 3 )" >> $GITHUB_ENV


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.TAG1 }} |
            ${{ env.TAG2 }}
          push: true
